#!/bin/sh
# Build the movement kernel: kernel.c -> kernel.wasm -> kernel-b64.js.
# zig cc is the toolchain (brew install zig); wasm32-freestanding, no libc.
# The stack flags matter: the C shadow stack lives in the low 8KB and the
# pool map starts at 16384 - see the memory map at the top of kernel.c.
set -e
cd "$(dirname "$0")"
zig cc -target wasm32-freestanding -O2 -nostdlib \
  -Wl,--no-entry -Wl,-z,stack-size=8192 \
  -Wl,--initial-memory=65536 -Wl,--max-memory=65536 \
  kernel.c -o kernel.wasm
# the browser loader: the module inlined as base64, armed by ?kernel=wasm -
# synchronous instantiation, so game.js sees window._wasmKernel at eval time
# (the module is ~10KB; sync compile at this size is fine on the main thread)
node -e '
const fs = require("fs");
const b64 = fs.readFileSync("kernel.wasm").toString("base64");
fs.writeFileSync("kernel-b64.js",
  "// GENERATED by tools/kernel/build.sh - do not edit (edit kernel.c)\n" +
  "// Arms the movement kernel in the browser when the URL says ?kernel=wasm.\n" +
  "(function () {\n" +
  "  if (!/[?&]kernel=wasm/.test(location.search)) return;\n" +
  "  try {\n" +
  "    const bytes = Uint8Array.from(atob(\"" + b64 + "\"), (c) => c.charCodeAt(0));\n" +
  "    const inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {});\n" +
  "    window._wasmKernel = { exports: inst.exports, memory: inst.exports.memory };\n" +
  "  } catch (e) { console.warn(\"kernel failed to arm, running the JS reference:\", e); }\n" +
  "})();\n");
console.log("kernel-b64.js written,", Math.round(b64.length / 1024) + "KB");
'
