apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-receipts
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-receipts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-receipts
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-runner
