// gen-luts — offline generator for slice 1's baked integer tables (numeric
// core; design/cs35-research/numeric-formats.md §4.1/§4.2). Run it, paste its
// stdout into game.js at the slice-1 landing, and never call Math.pow at
// runtime again. The Doom tables.c discipline: the table ships as literals,
// the generator ships beside it as the receipt.
//
//   node tools/gen-luts.mjs          emit the literal blocks
//   node tools/gen-luts.mjs --test   verify each entry against the float
//                                    formula (exact round to Q16 / exact ceil)

// priceAppeal: pow(1/m, 1.2) clamped 0.6..1.6, where m = priceMul walks the
// 0.70..1.30 board in 0.05 steps - exactly 13 values, indexed n = 14..26
// with m = n/20. Q16: 65536 = 1.0.
function priceAppealLut() {
  const lut = {};
  for (let n = 14; n <= 26; n++) {
    lut[n] = Math.round(65536 * Math.max(0.6, Math.min(1.6, Math.pow(20 / n, 1.2))));
  }
  return lut;
}

// upCost: ceil(base * mult^e) with e = lvl (chef: lvl-2), per the UPS table.
// Emitted per key over every exponent the lvl range can produce.
const UPS_DEF = {
  chef: { base: 60, mult: 2.0, max: 6, exps: [0, 1, 2, 3, 4] },      // lvl 2..6 -> e 0..4
  grill: { base: 120, mult: 1.6, max: 2, exps: [0, 1, 2] },
  board: { base: 90, mult: 1.6, max: 2, exps: [0, 1, 2] },
  table: { base: 60, mult: 1.5, max: 4, exps: [0, 1, 2, 3, 4] },
  juicebar: { base: 400, mult: 1, max: 1, exps: [0, 1] },
  arcade: { base: 650, mult: 1, max: 1, exps: [0, 1] },
  cadegear: { base: 180, mult: 1, max: 1, exps: [0, 1] },
};
function upCostTables() {
  const out = {};
  for (const k in UPS_DEF) {
    const u = UPS_DEF[k];
    out[k] = u.exps.map(e => Math.ceil(u.base * Math.pow(u.mult, e)));
  }
  return out;
}

function emit() {
  const lut = priceAppealLut();
  console.log(`// PRICE APPEAL, BAKED (numeric core slice 1). The board walks 0.70..1.30 in
// 0.05 steps - thirteen values, indexed by priceIdx n = 14..26 (m = n/20) -
// so pow(1/m, 1.2) is a table, not a transcendental. Q16: 65536 = x1.0.
// Generated by tools/gen-luts.mjs (${new Date().toISOString().slice(0, 10)}); regenerate there,
// never recompute here - Math.pow is implementation-approximated and banned
// from the sim (design/cs35-numeric-core.md, the arithmetic contract).
const PRICE_APPEAL_Q16 = {`);
  for (let n = 14; n <= 26; n++) {
    const m = (n / 20).toFixed(2);
    console.log(`  ${n}: ${lut[n]},${" ".repeat(7 - String(lut[n]).length)}// m ${m}  -> x${(lut[n] / 65536).toFixed(4)}`);
  }
  console.log(`};

// UPGRADE COSTS, BAKED: ceil(base * mult^e), e = lvl (chef: lvl - 2).
// Same receipt as above; the float formula retires with slice 1.
const UP_COST_C = {   // integer CENTS per exponent step`);
  const tables = upCostTables();
  for (const k in tables) {
    console.log(`  ${k}: [${tables[k].map(d => d * 100).join(", ")}],`);
  }
  console.log(`};`);
}

function test() {
  let fail = 0, n = 0;
  const lut = priceAppealLut();
  for (let idx = 14; idx <= 26; idx++) {
    n++;
    const want = 65536 * Math.max(0.6, Math.min(1.6, Math.pow(1 / (idx / 20), 1.2)));
    if (Math.abs(lut[idx] - want) > 0.5) { console.log(`FAIL  lut[${idx}] = ${lut[idx]}, float says ${want}`); fail++; }
  }
  // the 20/n vs 1/(n/20) identity holds exactly for these thirteen values
  const tables = upCostTables();
  for (const k in tables) tables[k].forEach((v, e) => {
    n++;
    const want = Math.ceil(UPS_DEF[k].base * Math.pow(UPS_DEF[k].mult, e));
    if (v !== want) { console.log(`FAIL  upCost ${k}[${e}] = ${v}, float says ${want}`); fail++; }
  });
  // documented spot values from the BIZ comment: table $60/90/135/203
  n++;
  const t = tables.table;
  if (!(t[0] === 60 && t[1] === 90 && t[2] === 135 && t[3] === 203)) { console.log("FAIL  table costs moved off the documented 60/90/135/203"); fail++; }
  console.log(`${n - fail}/${n} passed`);
  process.exit(fail ? 1 : 0);
}

if (process.argv.includes("--test")) test();
else emit();
