// TURN A VETTING PASS INTO A SHIPPED PLAYLIST.
//
// The back half of the record box. The box judges candidates in the browser and
// exports music-picks.json; this writes music/playlist.js, which the game loads
// in preference to its code literal -
// the same BUNDLED_* + literal-as-fallback shape the cultureways already use,
// so there is one idiom in this codebase for "data that may or may not be
// there" rather than two.
//
// TRACKS STREAM, THEY DO NOT SHIP. Matt, 2026-08-24: "would be much better if
// it loaded each track as needed; then we could have the whole playlist." He is
// right, and it dissolves the budget rather than managing it: an entry carries
// the CDN url, the browser fetches a track when it plays it, and the repo
// carries none of the 4.3 GB. A thousand-track playlist costs about 90 KB of
// JSON instead of ninety megabytes of audio.
//
// VERIFIED before relying on it (2026-08-24): cdn1.suno.ai is S3 behind
// CloudFront, answers 206 with range support so a browser can stream and seek,
// needs no auth, and enforces no referer check. An <audio> element playing a
// cross-origin file needs no CORS headers, unlike fetch or Web Audio.
//
// THE RISK, stated plainly because it is real: this is somebody else's CDN.
// If suno rotates those URLs the music stops, and offline play is gone. The
// hedge is --local, which copies a small core set into music/ so a town is
// never silent; the long tail streams.
//
//   node tools/mkplaylist.mjs [--picks music-picks.json] [--local 0]
import { readFileSync, writeFileSync, copyFileSync, existsSync, statSync, mkdirSync } from "fs";
import { join } from "path";
import { archiveMp3Dir } from "./archivepath.mjs";

const arg = (k, d) => {
  const i = process.argv.indexOf("--" + k);
  return i >= 0 ? process.argv[i + 1] : d;
};
const PICKS = arg("picks", "music-picks.json");
// How many tracks to also COPY locally, as the hedge against the CDN. 0 means
// pure streaming. These are chosen from the front of the kept list so the
// choice is yours (the box's order), not a sample.
const LOCAL = +arg("local", 0);

if (!existsSync(PICKS)) {
  console.error("no " + PICKS + " - export one from the in-game record box (MUS -> EXPORT)");
  process.exit(1);
}
const picks = JSON.parse(readFileSync(PICKS, "utf8"));
const cat = existsSync("music/catalog.json")
  ? JSON.parse(readFileSync("music/catalog.json", "utf8")) : { archive: "", tracks: [] };
const archiveDir = archiveMp3Dir(cat);

// A FILENAME THE REPO CAN LIVE WITH. The archive's names carry dates, spaces
// and a hash; music/ has always held short kebab-case files and the git history
// is easier to read when that stays true.
const slug = (name) => name.toLowerCase()
  .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "track";

mkdirSync("music", { recursive: true });

const byId = new Map((cat.tracks || []).map(t => [t.id, t]));
const rows = [];
const seenSlug = new Set();
let bytes = 0, noSrc = 0, localN = 0;
for (const k of picks.keep || []) {
  const c = byId.get(k.id) || {};
  const url = k.url || c.url || "";
  const arch = join(archiveDir, k.file || c.file || "");
  // The first --local N kept tracks are copied in; the rest stream. A track
  // with neither a local copy nor a url cannot play and is refused below.
  if (localN < LOCAL && existsSync(arch)) {
    let base = slug(k.name), n = 1;
    while (seenSlug.has(base)) base = slug(k.name) + "-" + (++n);   // slugs collide where names did not
    seenSlug.add(base);
    const dst = join("music", base + ".mp3");
    copyFileSync(arch, dst);
    bytes += statSync(dst).size;
    localN++;
    rows.push({ src: dst, name: k.name, e: k.e == null ? 1 : k.e });
    continue;
  }
  if (!url) { console.error("  NO SOURCE for " + (k.name || k.id)); noSrc++; continue; }
  rows.push({ src: url, name: k.name, e: k.e == null ? 1 : k.e });
}

const mb = bytes / (1024 * 1024);
if (noSrc) {
  console.error(noSrc + " kept tracks had neither a local file nor a url - refusing to write "
    + "a playlist that lies about what plays");
  process.exit(1);
}

const body = "// GENERATED by tools/mkplaylist.mjs from a record-box export - do not hand-edit.\n"
  + "// The game prefers this over its code literal when present; the literal stays\n"
  + "// as the fallback, the same shape the cultureways use.\n"
  + "var BUNDLED_PLAYLIST = " + JSON.stringify(rows, null, 1) + ";\n"
  + 'if (typeof window !== "undefined") window.BUNDLED_PLAYLIST = BUNDLED_PLAYLIST;\n';
writeFileSync("music/playlist.js", body);

const byE = {};
for (const r of rows) byE[r.e] = (byE[r.e] || 0) + 1;
console.log("wrote music/playlist.js - " + rows.length + " tracks ("
  + localN + " local, " + (rows.length - localN) + " streamed), "
  + mb.toFixed(1) + " MB added to the repo; energy spread "
  + Object.keys(byE).sort().map(e => e + ":" + byE[e]).join(" "));
if (!rows.some(r => r.e === 0) || !rows.some(r => r.e === 2)) {
  console.log("  NOTE: pickTrack matches energy to what the town is doing. A playlist "
    + "missing an energy band will fall back to whatever exists, so the music stops "
    + "tracking the game.");
}
