#!/usr/bin/env node
// mkversion.mjs — writes version.js, the build stamp the title screen shows.
//
// The stamp is the MERGE's identity: the orchestrator runs this at each merge
// before push (alongside mkcultureways.mjs), so the live site always says
// which commit it is. Deterministic for a given commit: the date is the
// COMMIT's date (%cs), never the wall clock, so regeneration reproduces.
//
// SHA resolution: `git rev-parse` where a git binary exists; else .git/HEAD
// the way tools/kube-arm.mjs reads it (node:26-slim has no git — a detached
// pod checkout leaves the raw SHA there). Worktrees keep .git as a pointer
// file, which the fallback follows one hop.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

function sh(cmd) {
  return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
}

let sha = "", date = "";
try {
  sha = sh("git rev-parse --short=7 HEAD");
  date = sh("git show -s --format=%cs HEAD");
} catch {
  try {
    let head = readFileSync(".git", "utf8").startsWith("gitdir:")
      ? readFileSync(readFileSync(".git", "utf8").slice(7).trim() + "/HEAD", "utf8").trim()
      : readFileSync(".git/HEAD", "utf8").trim();
    if (head.startsWith("ref: ")) {
      const ref = head.slice(5);
      head = existsSync(".git/" + ref) ? readFileSync(".git/" + ref, "utf8").trim() : "";
    }
    sha = head.slice(0, 7);
  } catch { /* no repo at all */ }
}
if (!/^[0-9a-f]{7}$/.test(sha)) { console.error("mkversion: no resolvable HEAD sha"); process.exit(1); }

const out = `// GENERATED by tools/mkversion.mjs - do not edit. The stamp is the merge's identity.
const GAME_BUILD = { sha: "${sha}", date: "${date}" };
`;
writeFileSync("version.js", out);
console.log(`wrote version.js — build ${sha}${date ? " " + date : ""}`);
