#!/usr/bin/env node
// mkversion.mjs — writes version.js, the build stamp the title screen shows.
//
// The stamp is the MERGE's identity: the orchestrator runs this at each merge
// before push (alongside mkcultureways.mjs), so the live site always says
// which commit it is. Deterministic for a given commit: the date is the
// COMMIT's date (%cs) and `t` is the COMMIT's epoch (%ct), never the wall
// clock, so regeneration reproduces byte-for-byte.
//
// `t` IS THE TICKING AGE'S ANCHOR. The title screen reads it and counts up
// live ("PUBLISHED 12M 5S AGO"), which is what tells a remote play-tester
// whether they are looking at the build that just landed or a cached one.
// It is the commit's time, not the publish's — the merge, the stamp commit
// and the Pages build are minutes apart, so the age is honest to about a
// minute and never claims more precision than that.
//
// SHA resolution: `git rev-parse` where a git binary exists; else .git/HEAD
// the way tools/kube-arm.mjs reads it (node:26-slim has no git — a detached
// pod checkout leaves the raw SHA there). Worktrees keep .git as a pointer
// file, which the fallback follows one hop.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

function sh(cmd) {
  return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
}

let sha = "", date = "", t = 0;
try {
  sha = sh("git rev-parse --short=7 HEAD");
  date = sh("git show -s --format=%cs HEAD");
  t = parseInt(sh("git show -s --format=%ct HEAD"), 10) || 0;
} catch {
  try {
    let head = readFileSync(".git", "utf8").startsWith("gitdir:")
      ? readFileSync(readFileSync(".git", "utf8").slice(7).trim() + "/HEAD", "utf8").trim()
      : readFileSync(".git/HEAD", "utf8").trim();
    if (head.startsWith("ref: ")) {
      const ref = head.slice(5);
      head = existsSync(".git/" + ref) ? readFileSync(".git/" + ref, "utf8").trim() : "";
    }
    sha = head.slice(0, 7);
  } catch { /* no repo at all */ }
}
if (!/^[0-9a-f]{7}$/.test(sha)) { console.error("mkversion: no resolvable HEAD sha"); process.exit(1); }

// The git-less fallback resolves a sha but no commit time. `t: 0` is the
// honest reading of that, and the title screen shows the plain stamp with no
// age line rather than counting up from 1970.
const out = `// GENERATED by tools/mkversion.mjs - do not edit. The stamp is the merge's identity.
const GAME_BUILD = { sha: "${sha}", date: "${date}", t: ${t} };
`;
writeFileSync("version.js", out);
console.log(`wrote version.js — build ${sha}${date ? " " + date : ""}${t ? " t=" + t : " (no commit time)"}`);
